input = "vplgs ubl, owbruslq eo qks alptswvs, pv retswlsm fz qks vbus ybhv qkbq nwsvpms etsw qks ksbtslv, pq pv fz le usblv bfvawm qe vsbwgk qksws bfets oew qks qksusv eo eaw yptsv, oew qkevs owprpm vzunbqkpsv qkbq nbwqpgpnbqs pl eaw bgkpstsuslqv bv hsyy bv eaw fyalmswplrv. - ubwraswpqs zeawgslbw"
ngram_path = "./" 
dictionary = "../wordlists/words_alpha.txt"
iters = 10_000 
aggression = [20, 30, 40, 60]
max_temp = 3 
min_temp = 5e-6
restarts = 1 
char_ngram_upweight = [0.01, 0.1, 0.5, 1.0]
word_ngram_upweight = [0.01, 0.1, 1.0]
word_upweight = [0.01, 0.1, 1.0]
max_char_ngram = 4
fixed = ""
freq_smoothing = [1e-1, 1e-4, 1e-7]
word_freq_smoothing = [1e-1, 1e-4, 1e-7]
keep_top = 3
plot = false
verbose = false
hyperparameters = ["aggression", "char_ngram_upweight", "word_ngram_upweight", "word_upweight", "freq_smoothing", "word_freq_smoothing"]
